### PR TITLE
Migrate to yarn

### PR DESCRIPTION
**Pull request by TrySound**
package-lock.json just doesn't work. I run `npm` and lockfile is
changed. I think this makes it useless. Yarn provides more stability
here.

### CODE REVIEW

**Comment by kof** [comment]
I agree, since I started using yarn, I forgot all the problems with lockfiles.

**Review by kof — APPROVED** [review]

**Comment by TrySound** [comment]
@iamstarkov Friendly ping. I will provide esm support after this PR.

**Comment by TrySound** [comment]
Are you okay with this @iamstarkov ?

**Comment by iamstarkov** [comment]
@TrySound I'm surprised this project isn't using yarn as of now. im on board with moving to yarn

**Comment by iamstarkov** [comment]
@TrySound  nice note about esm support, thank you

**Comment by TrySound** [comment]
Cool. Could you merge please?

**Comment by iamstarkov** [comment]
@TrySound I sent you an invite to collaborate

**Comment by TrySound** [comment]
Cool, thanks

**Pull request merged**
