### PR TITLE
pure jss example without react-jss

### PR DESCRIPTION
**Pull request by kof**

### CODE REVIEW

**Comment by kof** [comment]
my editor removed spaces btw

**Comment by kof** [comment]
when doing jss examples I always use presets in order to have a unified syntax.

**Comment by iamstarkov** [comment]
@kof thanks for pure jss example.

i fixed some stuff (removed object spread operator 'cause its stage-3 and fixed markdown ), pls take a look

**Comment by kof** [comment]
look good

**Comment by iamstarkov** [comment]
thanks

**Pull request merged**
